language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip3 install -r requirements.txt
  - pip3 install -e .
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install coveralls
script:
  - pytest --cov=./
after_success:
  - coveralls